test_mission:
  waypoint_1:
    x_m: 6.087
    y_m: 5.796
    yaw_rad: 0
  waypoint_2:
    x_m: 7.262
    y_m: 4.971
    yaw_rad: 0
  waypoint_3:
    x_m: 7.919
    y_m: 3.694
    yaw_rad: 0
  waypoint_4:
    x_m: 7.907
    y_m: 2.258
    yaw_rad: 0
  waypoint_5:
    x_m: 7.229
    y_m: 0.992
    yaw_rad: 0
  waypoint_6:
    x_m: 6.040
    y_m: 0.186
    yaw_rad: 0
  waypoint_7:
    x_m: 4.614
    y_m: 0.025
    yaw_rad: 0
  waypoint_8:
    x_m: 3.275
    y_m: 0.545
    yaw_rad: 0
  waypoint_9:
    x_m: 2.332
    y_m: 1.628
    yaw_rad: 0
  waypoint_10:
    x_m: 2.000
    y_m: 3.025
    yaw_rad: 0
  waypoint_11:
    x_m: 2.355
    y_m: 4.416
    yaw_rad: 0
  waypoint_12:
    x_m: 3.316
    y_m: 5.483
    yaw_rad: 0
  waypoint_13:
    x_m: 4.663
    y_m: 5.981
    yaw_rad: 0