frames:
  base: base_link
  reference: tracking_camera_odom

topics:
  waypoint: /move_base_simple/goal

settings:
  distance_tolerance: 0.6
  angle_tolerance: 0.7
  skip_countdown: 60
  skip_countdown_decrement: 1
